# Generated by Django 3.2 on 2021-07-29 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uid', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('date_publish', models.DateField(null=True)),
                ('title', models.CharField(max_length=1000, null=True)),
                ('link', models.CharField(max_length=1000, null=True)),
                ('state', models.IntegerField(choices=[(1, 'Da Ristrutturare'), (2, 'Buono / Abitabile'), (3, 'Ottimo / Ristrutturato'), (4, 'Nuovo / In costruzione'), (5, 'N.D.')], null=True)),
                ('text', models.TextField(max_length=5000, null=True)),
                ('price', models.FloatField(null=True)),
                ('price_mq', models.FloatField(null=True)),
                ('mq', models.FloatField(null=True)),
                ('costs', models.IntegerField(blank=True, null=True)),
                ('is_interesting', models.BooleanField(default=False)),
                ('is_hidden', models.BooleanField(default=False)),
                ('is_private', models.BooleanField(null=True)),
                ('has_changed', models.BooleanField(default=False)),
                ('note', models.TextField(blank=True, max_length=5000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=1000)),
                ('link', models.CharField(blank=True, max_length=1000, null=True)),
                ('platform', models.IntegerField(choices=[(1, 'Immobiliare'), (2, 'Casa Da Privato')])),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=1000, null=True)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.house')),
            ],
        ),
        migrations.AddField(
            model_name='house',
            name='search',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.search'),
        ),
    ]
