# Generated by Django 3.2 on 2021-04-29 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='costs',
            field=models.IntegerField(),
        ),
    ]
