# Generated by Django 3.2 on 2021-04-29 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_house_costs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='costs',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
