# Generated by Django 3.2 on 2021-04-29 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_alter_house_costs'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='exist_check',
            field=models.BooleanField(default=False),
        ),
    ]
