# Generated by Django 3.2 on 2021-04-29 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_house_exist_check'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='exist_check',
        ),
    ]
