# Generated by Django 3.2 on 2021-04-29 14:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_remove_house_exist_check'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 29, 14, 13, 25, 769778, tzinfo=utc)),
        ),
    ]
