# Generated by Django 3.2 on 2021-04-29 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_alter_house_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
