# Generated by Django 3.2 on 2021-04-29 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_alter_house_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='is_interesting',
            field=models.BooleanField(default=False),
        ),
    ]
