# Generated by Django 3.2 on 2021-05-05 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_house_is_interesting'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='has_changed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='house',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
    ]
