# Generated by Django 3.2 on 2021-05-05 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_auto_20210505_0944'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='is_hidden',
        ),
    ]
