# Generated by Django 3.2 on 2021-05-05 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_remove_house_is_hidden'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
    ]
