# Generated by Django 3.2 on 2021-05-05 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_house_is_hidden'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='state',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
