# Generated by Django 3.2 on 2021-05-05 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_house_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='state',
            field=models.CharField(choices=[(0, 'Tutti'), (1, 'Da Ristrutturare'), (2, 'Buono / Abitabile'), (3, 'Ottimo / Ristrutturato'), (4, 'Nuovo / In costruzione'), (5, 'N.D.')], max_length=100),
        ),
    ]
