# Generated by Django 3.2 on 2021-05-05 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_alter_house_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='state',
            field=models.IntegerField(choices=[(1, 'Da Ristrutturare'), (2, 'Buono / Abitabile'), (3, 'Ottimo / Ristrutturato'), (4, 'Nuovo / In costruzione'), (5, 'N.D.')]),
        ),
    ]
