# Generated by Django 3.2 on 2021-05-06 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0019_alter_search_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='searches',
            field=models.ManyToManyField(to='backend.Search'),
        ),
    ]
