# Generated by Django 3.2 on 2021-05-06 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0020_house_searches'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='date_publish',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='link',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='mq',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='price',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='price_mq',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='text',
            field=models.TextField(max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='title',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
