# Generated by Django 3.2 on 2021-05-06 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0021_auto_20210506_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='state',
            field=models.IntegerField(choices=[(1, 'Da Ristrutturare'), (2, 'Buono / Abitabile'), (3, 'Ottimo / Ristrutturato'), (4, 'Nuovo / In costruzione'), (5, 'N.D.')], null=True),
        ),
    ]
