# Generated by Django 3.2 on 2021-05-06 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0022_alter_house_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=1000, null=True)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.house')),
            ],
        ),
    ]
