# Generated by Django 3.2 on 2021-05-07 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0025_auto_20210507_0921'),
    ]

    operations = [
        migrations.RenameField(
            model_name='house',
            old_name='searches',
            new_name='search',
        ),
    ]
