# Generated by Django 3.2 on 2021-05-07 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0026_rename_searches_house_search'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='uid',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='house',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
