# Generated by Django 3.2 on 2021-05-07 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0027_auto_20210507_0944'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='note',
            field=models.TextField(max_length=5000, null=True),
        ),
    ]
