# Generated by Django 3.2 on 2021-05-07 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0028_house_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='note',
            field=models.TextField(blank=True, default=None, max_length=5000),
            preserve_default=False,
        ),
    ]
