# Generated by Django 3.2 on 2021-05-07 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0029_alter_house_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='note',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
    ]
