# Generated by Django 3.2 on 2021-05-11 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0031_alter_house_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='note',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='search',
            name='link',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
