# Generated by Django 3.2 on 2021-05-11 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0032_auto_20210511_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='link',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
