# Generated by Django 3.2 on 2021-05-15 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0034_house_is_private'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='is_private',
            field=models.BooleanField(),
        ),
    ]
