# Generated by Django 3.2 on 2021-05-11 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0034_search_platform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='platform',
            field=models.IntegerField(choices=[(1, 'Immobiliare'), (2, 'Casa Da Privato')], max_length=1000),
        ),
    ]
