# Generated by Django 3.2 on 2021-07-29 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0036_alter_house_is_private'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
